In [24]:
import torch
from torch import nn
from torch.optim import Adam


In [185]:

1/1.4142

0.7071135624381276

In [237]:
torch.manual_seed(12)

wdec = torch.randn((4, 11))
wdec = wdec/wdec.norm(dim=0)
wdec = wdec.T

answer = 0.75 * (wdec[1] + wdec[2])
print(answer.norm())

coeffs0 = wdec @ answer

coefficients = nn.Parameter(torch.zeros(wdec.shape[0]))
# coefficients.data = torch.full((25,), 0.5)
# coefficients.data = torch.relu(coeffs0) - 0.01
coefficients.data = coeffs0
# coefficients.data[-1] = -1
coefficients.data[4:] = -2
print(coefficients.data)

optimizer = Adam([coefficients], lr=0.5)


for i in range(100):

    optimizer.zero_grad()
    activations = torch.relu(coefficients)

    forward = activations @ wdec
    mse = ((forward - answer) ** 2).mean()

    # mse = -torch.dot(forward/forward.norm(), answer)

    sparsity = (activations / (activations + 0.2)).sum()

    loss = mse #+ 0.05*sparsity
    
    loss.backward()

    optimizer.step()

    # print(coefficients.data)

print(coefficients.data)
print(loss, mse)
print(forward.detach())
print(answer)

tensor(0.9711)
tensor([-0.6663,  0.6287,  0.6287,  0.5395, -2.0000, -2.0000, -2.0000, -2.0000,
        -2.0000, -2.0000, -2.0000])
tensor([-0.6663,  0.7405,  0.7509,  0.0106, -2.0000, -2.0000, -2.0000, -2.0000,
        -2.0000, -2.0000, -2.0000])
tensor(4.0782e-06, grad_fn=<MeanBackward0>) tensor(4.0782e-06, grad_fn=<MeanBackward0>)
tensor([ 0.0089, -0.2989,  0.0726, -0.9218])
tensor([ 0.0107, -0.2990,  0.0691, -0.9213])


In [141]:
0.5305

0.7071135624381276

In [167]:
a = torch.randn((2))
b = torch.randn((2))

In [168]:
a, b

(tensor([ 1.9573, -0.3660]), tensor([-0.2266,  0.2805]))

In [169]:
a * b

tensor([-0.4435, -0.1027])

In [170]:
torch.dot(a, b)

tensor(-0.5462)